packages:
  - packages/*
  - crates/*
  - 'playground'

catalog:
  '@vitejs/plugin-vue': ^6.0.7
  '@vitest/browser-playwright': ^4.1.10
  'tsdown': ^0.22.7
  'typescript': ~6.0.3
  'vite': ^8.1.4
  'vitest': ^4.1.10
  'vue': ^3.5.39
  'vue-tsc': ^3.3.7
